config/routes.rb
Rails.application.routes.draw do
  post   '/form',     to: 'email#form'
  get    '/about',    to: 'pages#about'
  get    '/contact',  to: 'pages#contact'
  get    '/calendar', to: 'calendar#calendar'
  get    '/login',    to: 'sessions#new'
  post   '/login',    to: 'sessions#create'
  delete '/logout',   to: 'sessions#destroy'
  resources :users
  resources :events

  root 'calendar#calendar'
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  has_secure_password
  before_save { self.email = email.downcase }
  before_save { self.login = login.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/
  validates :name, presence: true
  validates :login, presence: true,
                    uniqueness: true,
                    length: { in: 6..20,
                              too_short: 'Login muito curto',
                              too_long: 'Login muito longo' }
  validates :email, presence: true,
                    uniqueness: { case_sensitive: false },
                    format: { with: VALID_EMAIL_REGEX }
  validates :password, presence: true,
                       confirmation: true,
                       length: { minimum: 6 },
                       on: :create

  def self.digest(string)
    cost = if ActiveModel::SecurePassword.min_cost
             BCrypt::Engine::MIN_COST
           else
             BCrypt::Engine.cost
           end
    BCrypt::Password.create(string, cost: cost)
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :reload, only: %i[index create destroy update]
  before_action :permission

  def index
    reload
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save(user_params)
      redirect_to users_path
    else
      render new_user_path
    end
  end

  def show; end

  def destroy
    @user = nil if @user.destroy do
      redirect_to users_path
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user == @user.update_attributes(user_params)
      flash[:success] = 'Profile atualizado com sucesso'
      redirect_to users_path
    else
      flash[:danger] = 'Problema com atualização encontrada'
      redirect_to edit_user_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:name,
                                 :login,
                                 :email,
                                 :password,
                                 :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def reload
    @users = User.order(:name).page params[:page]
  end

  def permission
    render file: 'public/401' unless logged_in?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user do |form| %>
  <%= render 'shared/error_messages' %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control', :value => @user.name %>
  </div>

  <div class="field">
    <%= form.label :login %>
    <%= form.text_field :login, class: 'form-control', :value => @user.login %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email, class: 'form-control', :value => @user.email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, class: 'form-control' %>
  </div>

  <div class="actions">
    </br>
    <%= form.submit yield(:button_text), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/users/_form_edit.html.erb
<%= form_for @user, {action: "edit"} do |form| %>
  <%= render 'shared/error_messages' %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control', :value => @user.name %>
  </div>

  <div class="field">
    <%= form.label :login %>
    <%= form.text_field :login, class: 'form-control', :value => @user.login %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email, class: 'form-control', :value => @user.email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, class: 'form-control' %>
  </div>

  <div class="actions">
    </br>
    <%= form.submit "Editar", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Editar usuário") %>
<% provide(:button_text, "Editar usuário") %>
<h1><center><%= @user.name %></center></h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= render 'form', user: @user %>
		<center>
			<%= link_to 'Back', users_path %>
		</center>
	</div>
</div>

app/views/users/index.html.erb
<% provide(:title, "Lista de usuários") %>

<div class="right_col" role="main">
  <div class="">
    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_title">
            <h1><center>Lista de Usuários</center></h1>
          </div>

          <div class="col-xs-12 col-sm-12 col-md-12" align="left">
            <div class="col-xs-4 col-sm-4"><strong>Nome</strong></div>
            <div class="col-xs-2 col-sm-2"><strong>Login</strong></div>
            <div class="col-xs-4 col-sm-4"><strong>E-mail</strong></div>
            <div class="col-xs-2 col-sm-2"><strong><center>Ações</center></strong></div>
          </div>

          <div class="clearfix"></div>

          <% unless @users.nil? %>
            <% @users.each do |us| %>
              <div class="row-info col-xs-12 col-sm-12 col-md-12" align="left">
                <div class="col-xs-4 col-sm-4"><%= us.name %></div>
                <div class="col-xs-2 col-sm-2"><%= us.login %></div>
                <div class="col-xs-4 col-sm-4"><%= us.email %></div>
                <div class="col-xs-2 col-sm-2" id="symbol_access" >
                  <%= button_to user_path(us.id), :method => :get, :class => 'btn btn-success btn-sm', 'data-toggle' => 'tooltip', :title => 'Visualizar', 'id' => 'view-user-btn' do %>
                    <i class="fa fa-eye"></i>
                  <% end %>
                  <%= button_to user_path(us.id), :method => :delete, :class => 'btn btn-danger btn-sm', 'data-toggle' => 'tooltip', :title => 'Remover', data: { confirm: "Você tem certeza?" }, 'id' => 'remove-user-btn' do %>
                    <i class="fa fa-minus"></i>
                  <% end %>
                </div>
              </div>
            <% end %>
          <% end %>

          <div class="clearfix"></div>

          <center>
          <div style="margin-top: 1em">
              <%= link_to new_user_path, :method => :get, :class => 'btn btn-success btn-xs', 'data-toggle' => 'tooltip', :title => 'Cadastra um novo usuário', 'id' => 'grant-access-btn' do %>
                  <i class="fa fa-plus-square"></i>
              <% end %>
          </div>
          <% unless @users.nil? %>
            <%= paginate @users %>
          <% end %>
          </center>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, "Novo usuário") %>
<% provide(:button_text, "Criar usuário") %>
<% provide(:modelo, "user") %>

<h1><center>New User</center></h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= render 'form', user: @user %>
		<center>
			<%= link_to 'Back', users_path %>
		</center>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<!-- Would be wise to redo this view -->
<div align="left">
<h1><center><%= @user.name %></center></h1>

<table>
  <thead>
    <tr>
      <td>Nome</td>
      <td>Login</td>
      <td>Email</td>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><%= @user.name %></td>
      <td><%= @user.login %></td>
      <td><%= @user.email %></td>
    </tr>
  </tbody>
</table>
</div>

<div align="center">
<%= link_to 'Edit', edit_user_path %>
<%= link_to 'Back', users_path %>
</div>