config/routes.rb
Rails.application.routes.draw do
  post   '/form',     to: 'email#form'
  get    '/about',    to: 'pages#about'
  get    '/contact',  to: 'pages#contact'
  get    '/calendar', to: 'calendar#calendar'
  get    '/login',    to: 'sessions#new'
  post   '/login',    to: 'sessions#create'
  delete '/logout',   to: 'sessions#destroy'
  resources :users
  resources :events

  root 'calendar#calendar'
end

app/models/event.rb
# Model that validates everything
class Event < ApplicationRecord
  VALID_SITE_REGEX = %r[/((([A-Za-z]{3,9}:(?:\/\/)?)(?:[-;:&=\+\$,\w]+@)?
                        [A-Za-z0-9.-]+|(?:www.|[-;:&=\+\$,\w]+@)[A-Za-z0-9
                        .-]+)((?:\/[\+~%\/.\w-_]*)?\??(?:[-\+=&;%@.\w_]*)#
                        ?(?:[\w]*))?)/]
  validates :title, presence: true,
                    length: { in: 5..20,
                              too_short: ' pequeno demais',
                              too_long: ' longo demais' }
  validates :semester, presence: true,
                       numericality: { only_integer: true,
                                       in: 0..20 }
  validates :start, presence: true
  validates :end, allow_blank: true,
                  timeliness: { after: :start,
                                after_message: ' deve ser após start' }
  validates :url, format: { with: VALID_SITE_REGEX,
                            allow_blank: true }

  def print_semester
    ['Extra', 'Perfil 1', 'Perfil 2', 'Perfil 3', 'Perfil 4',
     'Perfil 5', 'Perfil 6', 'Perfil 7', 'Perfil 8', 'Optativa', 'Eventos']
  end
end

app/controllers/events_controller.rb
# Classe que controla os Eventos (provas, trabalhos, eventos em geral)
# relacionados ao curso
class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy]
  before_action :reload, only: %i[index create destroy update]
  before_action :permission

  def index
    reload
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save(event_params)
      redirect_to events_path
    else
      render new_event_path
    end
  end

  def show; end

  def destroy
    @event = nil if @event.destroy do
      redirect_to events_path
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event == @event.update_attributes(event_params)
      flash[:success] = 'Evento atualizado com sucesso'
      redirect_to events_path
    else
      flash[:danger] = 'Problema com atualização encontrada'
      redirect_to edit_event_path
    end
  end

  private

  def event_params
    params.require(:event).permit(:title,
                                  :semester,
                                  :start,
                                  :end,
                                  :allday,
                                  :repeating,
                                  :url)
  end

  def set_event
    @event = Event.find(params[:id])
  end

  def reload
    @events = Event.order(:title).page params[:page]
  end

  def permission
    render file: 'public/401' unless logged_in?
  end
end

app/views/events/_form.html.erb
<%= form_for novo = @event do |form| %>
  <%= render 'shared/error_messages' %>

  <div class="field">
    <%= form.label :title, 'Título' %>
    <%= form.text_field :title, class: 'form-control', :value => novo.title %>
  </div>

  <div class="form-group">
    <%= form.label :semester, 'Tipo' %>
    <select class="form-control" id=<%= :semester %> name='event[semester]' value=<%= novo.semester %>>
      <% novo.print_semester.each_with_index do | valor, number | %>
        <option value=<%= number %>><%= valor %></option>
      <% end %>
    </select>
  </div>

  <div class="field">
    <%= form.label :url, 'URL' %>
    <%= form.text_field :url, class: 'form-control', :value => novo.url %>
  </div>

  <div class="field">
    <%= form.label :start, 'Data início' %>
    <%= form.text_field :start, id: 'datepickerstart', class: 'form-control', :value => novo.start %>
  </div>

  <div class="field">
    <%= form.label :end, 'Data fim' %>
    <%= form.text_field :end, id: 'datepickerend', class: 'form-control', :value => novo.end %>
  </div>

  <div class="field">
    <%= form.label :repeating, 'Repetindo' %>
    <%= form.text_field :repeating, class: 'form-control', :value => novo.repeating %>
  </div>

  <div class="field">
    <%= form.check_box :allday, 'style': 'width: auto;' %>
    <%= form.label :allday, 'Dia inteiro', 'style': 'display: inline-block;' %>
  </div>

  <div class="actions">
    </br>
    <%= form.submit yield(:button_text), class: "btn btn-primary" %>
  </div>

  <%= javascript_include_tag 'datePicker/datePicker' %>
<% end %>

app/views/events/edit.html.erb
<% provide(:title, "Editar evento") %>
<% provide(:button_text, "Editar evento") %>
<h1><center><%= @event.title %></center></h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= render 'form', event: @event %>
		<center>
			<%= link_to 'Back', events_path %>
		</center>
	</div>
</div>

app/views/events/index.html.erb
<% provide(:title, "Lista de eventos") %>
<% provide(:modelo, "event") %>

<div class="right_col" role="main">
  <div class="">
    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_title">
            <h1><center>Lista de Eventos</center></h1>
          </div>

          <div class="col-xs-12 col-sm-12 col-md-12" align="left">
            <div class="col-xs-3 col-sm-3"><strong>Título</strong></div>
            <div class="col-xs-2 col-sm-2"><strong>Início</strong></div>
            <div class="col-xs-2 col-sm-2"><strong>Fim</strong></div>
            <div class="col-xs-2 col-sm-2 center"><strong>Tipo</strong></div>
            <div class="col-xs-1 col-sm-1 center"><strong>AD?</strong></div>
            <div class="col-xs-2 col-sm-2"><strong><center>Ações</center></strong></div>
          </div>

          <div class="clearfix"></div>

          <% unless @events.nil? %>
            <% @events.each do |ev| %>
              <div class="row-info col-xs-12 col-sm-12 col-md-12" align="left">
                <div class="col-xs-3 col-sm-3"><%= ev.title %></div>
                <div class="col-xs-2 col-sm-2"><%= ev.start %></div>
                <div class="col-xs-2 col-sm-2"><%= ev.end.presence || 'N/A' %></div>
                <div class="col-xs-2 col-sm-2 center"><%= ev.print_semester[ev.semester] %></div>
                <div class="col-xs-1 col-sm-1"><%= check_box_tag 'ad', '1', ev.allday, disabled: true %></div>
                <div class="col-xs-2 col-sm-2" id="symbol_access" >
                  <%= button_to event_path(ev.id), :method => :get, :class => 'btn btn-success btn-sm', 'data-toggle' => 'tooltip', :title => 'Visualizar', 'id' => 'view-user-btn' do %>
                    <i class="fa fa-eye"></i>
                  <% end %>
                  <%= button_to event_path(ev.id), :method => :delete, :class => 'btn btn-danger btn-sm', 'data-toggle' => 'tooltip', :title => 'Remover', data: { confirm: "Você tem certeza?" }, 'id' => 'remove-user-btn' do %>
                    <i class="fa fa-minus"></i>
                  <% end %>
                </div>
              </div>
            <% end %>
          <% end %>

          <div class="clearfix"></div>

          <center>
          <div style="margin-top: 1em">
              <%= link_to new_event_path, :method => :get, :class => 'btn btn-success btn-xs', 'data-toggle' => 'tooltip', :title => 'Cadastra um novo usuário', 'id' => 'grant-access-btn' do %>
                  <i class="fa fa-plus-square"></i>
              <% end %>
          </div>
          <% unless @events.nil? %>
            <%= paginate @events %>
          <% end %>
          </center>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<% provide(:title, "Novo evento") %>
<% provide(:button_text, "Criar evento") %>
<% provide(:modelo, "event") %>

<h1><center>New Event</center></h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= render 'form', event: @event %>
		<center>
			<%= link_to 'Back', events_path %>
		</center>
	</div>
</div>

app/views/events/show.html.erb
<% provide(:title, @event.title) %>
<!-- Would be wise to redo this view -->
<div align="left">
<h1><center><%= @event.title %></center></h1>

<table>
  <thead>
    <tr>
      <td>Título</td>
      <td>Início</td>
      <td>Fim</td>
      <td>Tipo</td>
      <td>Dia todo</td>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><%= @event.title %></td>
      <td><%= @event.start %></td>
      <td><%= @event.end %></td>
      <td><%= @event.print_semester[@event.semester] %></td>
      <td><%= check_box_tag 'ad', '1', @event.allday, disabled: true %></td>
    </tr>
  </tbody>
</table>
</div>

<div align="center">
<%= link_to 'Edit', edit_event_path %>
<%= link_to 'Back', events_path %>
</div>