config/routes.rb
Rails.application.routes.draw do
  post   '/form',     to: 'email#form'
  get    '/about',    to: 'pages#about'
  get    '/contact',  to: 'pages#contact'
  get    '/calendar', to: 'calendar#calendar'
  get    '/login',    to: 'sessions#new'
  post   '/login',    to: 'sessions#create'
  delete '/logout',   to: 'sessions#destroy'
  resources :users
  resources :events

  root 'calendar#calendar'
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="https://www.facebook.com/CACCS.UFSCar/">CACCS - UFSCar &reg;</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Sobre",   about_path %></li>
      <li><%= link_to "Contato", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-left">
        <%= link_to image_tag("shared/logo", :alt => "Home", :class => "logo", "style" => "width: 25px; height: 25px;"), root_path, id: "logo" %>
      </ul>
    </nav>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Calendário",   calendar_path %></li>      	
        <li><%= link_to "Ajuda",   	  '#' %></li>
        <% if logged_in? %>
          <li><%= link_to "Usuários",   users_path %></li>
          <li><%= link_to "Eventos",   events_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.name %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Perfil",  current_user %></li>
              <li><%= link_to "Configurações",  '#' %></li>
              <li class="divider"></li>
              <li><%= link_to "Logout",   logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in",   login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_show.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
    <%= favicon_link_tag %>
    <%= yield :scripts %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render partial: 'layouts/show', flash: flash %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>